const chapters = [
  {
    id: "san-francisco-1",
    place: "San Francisco",
    myth: "The beginning",
    modern: "California, USA",
    book: "Chapter 01",
    confidence: "Origin",
    query: "San Francisco California skyline",
    text: "The journey begins on the edge of the Pacific, in a city shaped by hills, fog, reinvention, and the promise of elsewhere.",
  },
  {
    id: "providence-1",
    place: "Providence",
    myth: "Across the continent",
    modern: "Rhode Island, USA",
    book: "Chapter 02",
    confidence: "Arrival",
    query: "Providence Rhode Island skyline",
    text: "The route crosses North America to Providence, a smaller city with an outsized place in the story.",
  },
  {
    id: "paris-1",
    place: "Paris",
    myth: "The first crossing",
    modern: "France",
    book: "Chapter 03",
    confidence: "Arrival",
    query: "Paris France Seine city",
    text: "Paris opens the journey beyond the Atlantic and becomes the first of several cities that will call the route back.",
  },
  {
    id: "beijing",
    place: "Beijing",
    myth: "Eastward",
    modern: "China",
    book: "Chapter 04",
    confidence: "New world",
    query: "Beijing China city Forbidden City",
    text: "The path turns east to Beijing, carrying the journey into a different scale of history, language, and urban life.",
  },
  {
    id: "paris-2",
    place: "Paris",
    myth: "The first return",
    modern: "France",
    book: "Chapter 05",
    confidence: "Return",
    query: "Paris France streets",
    text: "Paris returns as a familiar point on the map, changed by everything encountered since the first arrival.",
  },
  {
    id: "shanghai",
    place: "Shanghai",
    myth: "The river city",
    modern: "China",
    book: "Chapter 06",
    confidence: "Arrival",
    query: "Shanghai China Bund skyline",
    text: "Shanghai adds a fast-moving chapter on the Huangpu, where old neighborhoods and a futuristic skyline face one another.",
  },
  {
    id: "providence-2",
    place: "Providence",
    myth: "Back to the beginning",
    modern: "Rhode Island, USA",
    book: "Chapter 07",
    confidence: "Return",
    query: "Providence Rhode Island downtown",
    text: "The journey returns to Providence, revisiting an earlier chapter from a much wider horizon.",
  },
  {
    id: "paris-3",
    place: "Paris",
    myth: "A city in the rhythm",
    modern: "France",
    book: "Chapter 08",
    confidence: "Return",
    query: "Paris France city view",
    text: "Paris appears again, no longer only a destination but part of the recurring rhythm of the journey.",
  },
  {
    id: "san-francisco-2",
    place: "San Francisco",
    myth: "West again",
    modern: "California, USA",
    book: "Chapter 09",
    confidence: "Return",
    query: "San Francisco California Golden Gate",
    text: "The route returns to San Francisco and the Pacific, closing one long arc before another begins.",
  },
  {
    id: "los-angeles",
    place: "Los Angeles",
    myth: "Down the coast",
    modern: "California, USA",
    book: "Chapter 10",
    confidence: "Arrival",
    query: "Los Angeles California skyline",
    text: "A shorter move down the California coast leads to Los Angeles, a sprawling city of many centers and possible lives.",
  },
  {
    id: "buenos-aires-1",
    place: "Buenos Aires",
    myth: "South America",
    modern: "Argentina",
    book: "Chapter 11",
    confidence: "Arrival",
    query: "Buenos Aires Argentina city",
    text: "Buenos Aires begins the South American chapters with broad avenues, late nights, and a strong sense of movement.",
  },
  {
    id: "rio-de-janeiro",
    place: "Rio de Janeiro",
    myth: "Between mountain and sea",
    modern: "Brazil",
    book: "Chapter 12",
    confidence: "Arrival",
    query: "Rio de Janeiro Brazil city coast",
    text: "Rio de Janeiro places the journey between mountains and ocean, with the city unfolding around its dramatic landscape.",
  },
  {
    id: "medellin",
    place: "Medellín",
    myth: "The valley",
    modern: "Colombia",
    book: "Chapter 13",
    confidence: "Arrival",
    query: "Medellin Colombia city valley",
    text: "The route turns north to Medellín, a city gathered in a green Andean valley and transformed by connection.",
  },
  {
    id: "istanbul",
    place: "Istanbul",
    myth: "Between continents",
    modern: "Türkiye",
    book: "Chapter 14",
    confidence: "Crossroads",
    query: "Istanbul Turkey Bosphorus skyline",
    text: "Istanbul becomes the hinge between continents, where the route crosses the Bosphorus and layers of history meet.",
  },
  {
    id: "bali",
    place: "Bali",
    myth: "The far turn",
    modern: "Indonesia",
    book: "Chapter 15",
    confidence: "Arrival",
    query: "Bali Indonesia coast rice terraces",
    text: "Bali marks the far eastern turn of the journey, an island chapter of tropical landscapes and deep cultural continuity.",
  },
  {
    id: "buenos-aires-2",
    place: "Buenos Aires",
    myth: "A southern return",
    modern: "Argentina",
    book: "Chapter 16",
    confidence: "Return",
    query: "Buenos Aires Argentina Palermo",
    text: "Buenos Aires returns, now as a known city rather than a first encounter, adding another layer to the South American story.",
  },
  {
    id: "cape-town",
    place: "Cape Town",
    myth: "At the Cape",
    modern: "South Africa",
    book: "Chapter 17",
    confidence: "Arrival",
    query: "Cape Town South Africa Table Mountain",
    text: "Cape Town carries the route to the southern edge of Africa, framed by Table Mountain and two oceans.",
  },
  {
    id: "paris-4",
    place: "Paris",
    myth: "The fourth Paris",
    modern: "France",
    book: "Chapter 18",
    confidence: "Return",
    query: "Paris France rooftops",
    text: "The fourth Paris chapter shows how a place can remain the same on a map while becoming different with every return.",
  },
  {
    id: "milan",
    place: "Milan",
    myth: "The present chapter",
    modern: "Italy",
    book: "Chapter 19",
    confidence: "Now",
    query: "Milan Italy Duomo city",
    text: "The route arrives in Milan, the present chapter of a journey still in motion rather than a final destination.",
  },
];

const roman = [
  "I",
  "II",
  "III",
  "IV",
  "V",
  "VI",
  "VII",
  "VIII",
  "IX",
  "X",
  "XI",
  "XII",
  "XIII",
  "XIV",
  "XV",
  "XVI",
  "XVII",
  "XVIII",
  "XIX",
];

export const personalStops = chapters.map((chapter, index) => ({
  ...chapter,
  n: roman[index],
}));

export const recurringPlaces = [
  {
    id: "return-paris",
    myth: "Paris",
    place: "Four chapters",
    modern: "Paris, France",
    query: "Paris France Seine city",
    text: "Paris is the most persistent point on the route, appearing four times across the journey.",
    alternatives: [
      "03 · First arrival",
      "05 · First return",
      "08 · Third chapter",
      "18 · Fourth chapter",
    ],
  },
  {
    id: "return-san-francisco",
    myth: "San Francisco",
    place: "Two chapters",
    modern: "San Francisco, California",
    query: "San Francisco California Golden Gate city",
    text: "San Francisco holds both the opening chapter and a later return to the Pacific coast.",
    alternatives: ["01 · The beginning", "09 · West again"],
  },
  {
    id: "return-providence",
    myth: "Providence",
    place: "Two chapters",
    modern: "Providence, Rhode Island",
    query: "Providence Rhode Island city",
    text: "Providence appears twice, first as a major crossing and later as a return to an earlier chapter.",
    alternatives: ["02 · Across the continent", "07 · Back to the beginning"],
  },
  {
    id: "return-buenos-aires",
    myth: "Buenos Aires",
    place: "Two chapters",
    modern: "Buenos Aires, Argentina",
    query: "Buenos Aires Argentina city",
    text: "Buenos Aires anchors two separate South American chapters in the route.",
    alternatives: ["11 · South America", "16 · A southern return"],
  },
];

export const personalCoordinates = {
  "san-francisco-1": [37.7749, -122.4194],
  "providence-1": [41.824, -71.4128],
  "paris-1": [48.8566, 2.3522],
  beijing: [39.9042, 116.4074],
  "paris-2": [48.8666, 2.3422],
  shanghai: [31.2304, 121.4737],
  "providence-2": [41.834, -71.4028],
  "paris-3": [48.8466, 2.3622],
  "san-francisco-2": [37.7849, -122.4094],
  "los-angeles": [34.0522, -118.2437],
  "buenos-aires-1": [-34.6037, -58.3816],
  "rio-de-janeiro": [-22.9068, -43.1729],
  medellin: [6.2442, -75.5812],
  istanbul: [41.0082, 28.9784],
  bali: [-8.4095, 115.1889],
  "buenos-aires-2": [-34.6137, -58.3916],
  "cape-town": [-33.9249, 18.4241],
  "paris-4": [48.8766, 2.3722],
  milan: [45.4642, 9.19],
};
